all: baby_globe_book.gif baby_globe_laptop.gif baby_globe_newspaper.gif

baby_globe_book.gif:
	magick originals/baby_globe_book_full.gif -coalesce -repage 0x0 -crop 550x550+190+235 -resize 128x128 +repage baby_globe_book.gif

baby_globe_laptop.gif:
	magick originals/baby_globe_laptop_full.gif -coalesce -repage 0x0 -crop 620x620+170+285 -resize 128x128 +repage baby_globe_laptop.gif

baby_globe_newspaper.gif:
	magick originals/baby_globe_newspaper_full.gif -coalesce -repage 0x0 -crop 620x620+190+225 -resize 128x128 +repage baby_globe_newspaper.gif
