all: \
	icon.16.png \
	icon.16.light.png \
	icon.48.png \
	icon.48.light.png \
	icon.96.png \
	icon.96.light.png \
	;

icon.16.png:
	magick -background none -gravity center icon.png -resize 16x16 -extent 16x16 icon.16.png

icon.16.light.png:
	magick -background none -gravity center icon.png -resize 16x16 -extent 16x16 icon.16.light.png

icon.48.png:
	magick -background none -gravity center icon.png -resize 48x48 -extent 48x48 icon.48.png

icon.48.light.png:
	magick -background none -gravity center icon.png -resize 48x48 -extent 48x48 icon.48.light.png

icon.96.png:
	magick -background none -gravity center icon.png -resize 96x96 -extent 96x96 icon.96.png

icon.96.light.png:
	magick -background none -gravity center icon.png -resize 96x96 -extent 96x96 icon.96.light.png
